export const USER_ACTION_TYPES = {
    SET_CURRENT_USER: 'user/SET_CURRENT_USER',
<<<<<<< HEAD
    CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
    GOOGLE_SIGN_IN_START: 'user/GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'user/EMAIL_SIGN_IN_START',
=======
    CHECK_USER_SESSION:'user/CHECK_USER_SESSION',
    GOOGLE_SIGN_IN_START:'user/GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START:'user/EMAIL_SIGN_IN_START',
>>>>>>> 06261ce4d81f6424dd055e0b36de2d42fea0840e
    SIGN_IN_SUCCESS: 'user/SIGN_IN_SUCCESS',
    SIGN_IN_FAILED: 'user/SIGN_IN_FAILED',
};

